routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes([
	'register' => false,
	
]);

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/autor','AutorController')->except(['show']);
Route::resource('/editorial','EditorialController')->except(['show']);
Route::resource('/rol','RoleController')->except(['show']);
Route::resource('/usuario','UsuarioController')->except(['show']);
Route::resource('/libro','LibroController')->except(['show']);
Route::post('/porcentajea','PorcentajeController@aumentar')->name('porcentaje.aumentar');
Route::post('/porcentajed','PorcentajeController@disminuir')->name('porcentaje.disminuir');
Route::resource('aumentap','PorcentajeAumenta')->except(['create','store','destroy','show']);
Route::resource('restap','PorcentajeResta')->except(['create','store','destroy','show']);

resources/views/autores/create.blade.php
@extends('layouts.plantilla')
@section('styles')


@endsection    
 
@section('content')


		<div class="row">
			    <div class="col-lg-12 ">
			        <div class="panel">
			            <div class="panel-heading">
			                <h3 class="panel-title">Agregar Informacion del Autor</h3>
			            </div>
			
			
			            <!-- BASIC FORM ELEMENTS -->
			        <form action="{{ route('autor.store') }}" onsubmit="return esfechavalida() " method="post" name="forma" class="panel-body form-horizontal form-padding">
                        @csrf
                        <!--Static-->
                        @include('autores.form',['mensaje'=> 'crear'])
                                    
                     </form>
			            <!--===================================================-->
			            <!-- END BASIC FORM ELEMENTS -->
			
			
			        </div>
			    </div>

					   
		</div>
    


	
@endsection  
    
    


 @section('scripts')  
    
   
  


@endsection

resources/views/autores/edit.blade.php
@extends('layouts.plantilla')
@section('styles')


@endsection    
 
@section('content')
@include("partials.validacion")
@include("partials.validacionAutor")

		<div class="row">
			    <div class="col-lg-12 ">
			        <div class="panel">
			            <div class="panel-heading">
			                <h3 class="panel-title">Editar Informacion del Autor</h3>
			            </div>
			
			
			            <!-- BASIC FORM ELEMENTS -->
			            <!--===================================================-->
			            <form  action="{{ route('autor.update', $actualizar->id) }}" onsubmit="return esfechavalida() " name="forma" id="form1" method="post" class="panel-body form-horizontal form-padding">
			            	@csrf
			            	@method('PUT')
			
			           <div class="form-group">
		                <label class="col-md-3 control-label" for="demo-text-input">Nombres</label>
		                    <div class="col-md-9">
		                        <input type="text" name="sigi_nombres" value="{{ isset($actualizar->sigi_nombres) ? $actualizar->sigi_nombres : '' }}" id="demo-text-input" class="form-control" placeholder="Nombres">
		                        @error('sigi_nombres')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		                </div>
		
		                <!--Text Input-->
		                <div class="form-group">
		                    <label class="col-md-3 control-label" for="demo-text-input">Apellidos</label>
		                    <div class="col-md-9">
		                        <input type="text" name="sigi_apellidos" value="{{ isset($actualizar->sigi_apellidos) ? $actualizar->sigi_apellidos : ''  }}" id="demo-text-input" class="form-control" placeholder="Apellidos">
		                        @error('sigi_apellidos')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		                </div>
		
		                <!--Email Input-->
		                <div class="form-group">
		                    <label class="col-md-3 control-label" for="demo-email-input">Tipo DNI</label>
		                    <div class="col-md-9">
		                        <select name="sigi_tipo_dni" class="form-control">
		                        	<option>Seleccion tipo de dni</option>	
		                        	<option value="C" @if($actualizar->sigi_tipo_dni == 'C') selected=""  @endif) >Cedula Ciudadania</option>
		                        	<option value="P" @if($actualizar->sigi_tipo_dni == 'P') selected=""  @endif) >Pasaporte</option>
		                        </select>
		                         @error('sigi_tipo_dni')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		                </div>

		                 <div class="form-group">
		                    <label class="col-md-3 control-label" for="demo-text-input">Dni</label>
		                    <div class="col-md-9">
		                        <input type="number" id="documento" onblur="validarDocumento()" name="sigi_dni"  onKeyPress="return soloNumeros(event)" value="{{ isset($actualizar->sigi_dni) ? $actualizar->sigi_dni : ''  }}" id="demo-text-input" class="form-control" placeholder="Ingrese Dni">
		                         @error('sigi_dni')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		                </div>

		                <div class="form-group">
		                    <label class="col-md-3 control-label" for="demo-email-input">Sexo</label>
		                    <div class="col-md-9">
		                        <select name="sigi_sexo" class="form-control">
		                        	<option>Seleccion tipo de sexo</option>	
		                        	<option value="H" @if($actualizar->sigi_sexo == 'H') selected=""  @endif) >Hombre</option>
		                        	<option value="M" @if($actualizar->sigi_sexo == 'M') selected=""  @endif) >Mujer</option>
		                        </select>
		                        @error('sigi_sexo')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		                </div>

		                 <div class="form-group">
		                    <label class="col-md-3 control-label" for="demo-text-input">Fecha Nacimiento</label>
		                    <div class="col-md-9">
		                        <input type="text" id="fecha" onblur="esfechavalida();" name="sigi_fecha_autor" value="{{ isset($actualizar->sigi_fecha_autor) ? $actualizar->sigi_fecha_autor : ''  }}"  id="demo-text-input" class="form-control" placeholder="Ingrese Email">
		                        @error('sigi_fecha_autor')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		                </div>
		

		                 <div class="form-group">
		                    <label class="col-md-3 control-label" for="demo-text-input">Email</label>
		                    <div class="col-md-9">
		                        <input type="text" name="sigi_email" value="{{ isset($actualizar->sigi_email) ? $actualizar->sigi_email : ''  }}"   id="demo-text-input" class="form-control" placeholder="Ingrese Email">
		                        @error('sigi_email')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		                </div>

		                <div class="form-group">
		                    <label class="col-md-3 control-label" for="demo-email-input">Estado</label>
		                    <div class="col-md-9">
		                        <select name="sigi_estado" class="form-control">
		                        	<option>Seleccion de estado</option>	
		                        	<option value="A" @if($actualizar->sigi_estado == 'A') selected=""  @endif) >Activo</option>
		                        	<option value="I" @if($actualizar->sigi_estado == 'I') selected=""  @endif) >Inactivo</option>
		                        </select>
		                        @error('sigi_estado')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		                </div>
					
					              
					
					              
					
					              
					               
					 <div class="modal-footer">
	                    <a href="{{ route('autor.index') }}" class="btn btn-default" type="button">Close</a>
	                    <input type="submit" id="Guardar" class="btn btn-primary"  onclick="return confirm('Desea Actualizar?')" value="Actualizar Actor" name="">
                    
               		 </div>
			            </form>
			            <!--===================================================-->
			            <!-- END BASIC FORM ELEMENTS -->
			
			
			        </div>
			    </div>

					   
		</div>
    


	
@endsection  
    
    


 @section('scripts')  
    
   
  


@endsection

resources/views/autores/form.blade.php
@include("partials.validacion")
@include("partials.validacionAutor")


  					 <div class="form-group">
		                <label class="col-md-3 control-label" for="demo-text-input">Nombres</label>
		                    <div class="col-md-9">
		                        <input type="text"  id="nombres" value="{{ old('sigi_nombres') }}" name="sigi_nombres" value="{{ isset($actualizar->sigi_nombres) ? $actualizar->sigi_nombres : '' }}" id="demo-text-input" class="form-control" placeholder="Nombres">
		                        @error('sigi_nombres')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		                </div>
		
		                <!--Text Input-->
		                <div class="form-group">
		                    <label class="col-md-3 control-label" for="demo-text-input">Apellidos</label>
		                    <div class="col-md-9">
		                        <input type="text"  id="apellidos" value="{{ old('sigi_apellidos') }}" name="sigi_apellidos" value="{{ isset($actualizar->sigi_apellidos) ? $actualizar->sigi_apellidos : ''  }}" id="demo-text-input" class="form-control" placeholder="Apellidos">
		                        @error('sigi_apellidos')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		                </div>
		
		                <!--Email Input-->
		                <div class="form-group">
		                    <label class="col-md-3 control-label" for="demo-email-input">Tipo DNI</label>
		                    <div class="col-md-9">
		                        <select required="" name="sigi_tipo_dni" class="form-control">
		                        	<option value="">Seleccion tipo de dni</option>	
		                        	<option value="C" >Cedula Ciudadania</option>
		                        	<option value="P" >Pasaporte</option>
		                        </select>

		                        @error('sigi_tipo_dni')
									<span class="invalid-feedback d-block" role="alert">
										{{ $message }}
									</span>
									
								@enderror	
		                        
		                    </div>
		                </div>

		                 <div class="form-group">
		                    <label class="col-md-3  control-label" for="demo-text-input">Dni</label>
		                    <div class="col-md-9">
		                        <input type="number" value="{{ old('sigi_dni') }}" required="" id="documento" onblur="validarDocumento()" name="sigi_dni"  onKeyPress="return soloNumeros(event)" value="{{ isset($actualizar->sigi_dni) ? $actualizar->sigi_dni : ''  }}" id="demo-text-input" class="form-control" placeholder="Ingrese Dni">
		                         @error('sigi_dni')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		                </div>

		                <div class="form-group">
		                    <label class="col-md-3 control-label" for="demo-email-input">Sexo</label>
		                    <div class="col-md-9">
		                        <select required="" name="sigi_sexo" class="form-control">
		                        	<option value="">Seleccion tipo de sexo</option>	
		                        	<option value="H">Hombre</option>
		                        	<option value="M">Mujer</option>
		                        </select>

	                           @error('sigi_sexo')
								<span class="invalid-feedback d-block" role="alert">
									{{ $message }}
								</span>
								@enderror	
		                       
		                    </div>
		                </div>

		                 <div class="form-group">
		                    <label class="col-md-3 control-label" for="demo-text-input">Fecha Nacimiento</label>
		                    <div class="col-md-9">
		                        <input type="text"  id="fecha" value="{{ old('sigi_fecha_autor') }}"  name="sigi_fecha_autor" value="{{ isset($actualizar->sigi_fecha_autor) ? $actualizar->sigi_fecha_autor : ''  }}"  id="demo-text-input" class="form-control" placeholder="Ingrese fecha">
		                        @error('sigi_fecha_autor')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		                </div>
		

		                 <div class="form-group">
		                    <label class="col-md-3 control-label" for="demo-text-input">Email</label>
		                    <div class="col-md-9">
		                        <input type="text"  id="email" value="{{ old('sigi_email') }}" name="sigi_email" value="{{ isset($actualizar->sigi_email) ? $actualizar->sigi_email : ''  }}"   id="demo-text-input" class="form-control" placeholder="Ingrese Email">
		                        @error('sigi_email')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		                </div>         
								              
								              
					               
					<div class="modal-footer">
	                    <a href="{{ route('autor.index') }}" class="btn btn-default" type="button">Close</a>
	                    <input type="submit"  class="btn btn-primary"  onclick="return confirm('Desea Agregar?')" value="Crear Actor" name="">
                    
               		 </div>

               		

               		

resources/views/autores/index.blade.php
@extends('layouts.plantilla')
@section('styles')
    <!--DataTables [ OPTIONAL ]-->
    <link href="{{ asset('admin/plugins/datatables/media/css/dataTables.bootstrap.css') }}" rel="stylesheet">
    <link href="{{ asset('admin/plugins/datatables/extensions/Responsive/css/responsive.dataTables.min.css') }}" rel="stylesheet">

    

@endsection    
 


@section('content')
        <div class="panel">
                        <div class="panel-heading">
                            <h3 class="panel-title"> 
                                <a href="{{ route('autor.create') }}" style="color:white;" class="btn btn-warning btn-rounded">Agregar</a>

                            </h3>
                            @if(Session::has('Mensaje'))
                                 <div class="panel-body demo-nifty-alert">
                                    
                                    <div class="row">
                                        <div class="col-sm-12">
                            
                                            <!-- Primary Alert -->
                                            <!--===================================================-->
                                            <div class="alert alert-primary">
                                                <button class="close" data-dismiss="alert"><i class="pci-cross pci-circle"></i></button>
                                                <strong>Mensaje!</strong>  {{ Session::get('Mensaje') }}
                                            </div>
                            
                                            <!-- Success Alert -->
                                            <!--===================================================-->
                                           
                            
                                        </div>
                                      
                                    </div>
                                 </div>
                                   
                             @endif
                        </div>
                        <div class="panel-body">
                            <table id="demo-dt-basic" class="table table-striped table-bordered" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th>Nombres - Apellidos</th>                                 
                                        <th class="min-tablet">DNI.</th>
                                        <th class="min-desktop">Sexo</th>
                                        <th class="min-desktop">Fecha Nacim.</th>
                                        <th class="min-desktop">Email</th>
                                        <th class="min-desktop">Estado</th>
                                        <th>Eliminar</th>
                                        <th>Editar</th>
                                     
                                        
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($leer as $recorrer)
                                    <tr>
                                        <td>{{ $recorrer->sigi_nombres }} {{ $recorrer->sigi_apellidos }}</td>                               
                                        <td>{{ $recorrer->sigi_dni }}</td>
                                        <td>{{ $recorrer->sigi_sexo }}</td>
                                        <td>{{ $recorrer->sigi_fecha_autor }}</td>
                                        <td>{{ $recorrer->sigi_email }}</td>
                                        <td>{{ $recorrer->sigi_estado }}</td>
                                        <td>
                                            <form action="{{ route('autor.destroy',$recorrer->id) }}" method="post">
                                                @csrf
                                                @method('DELETE')
                                                  <button class="btn btn-success btn-icon" onclick="return confirm('Desea Eliminar?')"><i class="demo-psi-recycling icon-lg"></i></button>
                                            </form> 
                                            
                                        </td>
                                        <td>  
                                         

                                        
                                       
                                            <a class="btn btn-mint btn-icon" href="{{ route('autor.edit',$recorrer->id) }}" ><i class="demo-psi-pen-5 icon-lg"></i></a>
                                        </td>

                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
        </div>


    

        <!-- MODALES -->

    <div class="modal fade" id="demo-default-modal" role="dialog" tabindex="-1" aria-labelledby="demo-default-modal" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">

                <!--Modal header-->
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><i class="pci-cross pci-circle"></i></button>
                    <h4 class="modal-title text-center">Ingresar Autor </h4>
                </div>

                <!--Modal body-->
                <div class="modal-body">
                     <form action="{{ route('autor.store') }}" method="post" name="forma" class="panel-body form-horizontal form-padding">
                        @csrf
                        <!--Static-->
                        @include('autores.form',['mensaje'=> 'crear'])
                                    
                     </form>
                   
                </div>

                <!--Modal footer-->
             
            </div>
        </div>
    </div>
@endsection  
    
    
 

 @section('scripts')  
    
   
    <!--DataTables [ OPTIONAL ]-->
    <script src="{{ asset('admin/plugins/datatables/media/js/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('admin/plugins/datatables/media/js/dataTables.bootstrap.js') }}"></script>
    <script src="{{ asset('admin/plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js') }}"></script>


    <!--DataTables Sample [ SAMPLE ]-->
    <script src="{{ asset('admin/js/demo/tables-datatables.js') }}"></script>


@endsection