routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes([
	'register' => false,
	
]);

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/autor','AutorController')->except(['show']);
Route::resource('/editorial','EditorialController')->except(['show']);
Route::resource('/rol','RoleController')->except(['show']);
Route::resource('/usuario','UsuarioController')->except(['show']);
Route::resource('/libro','LibroController')->except(['show']);
Route::post('/porcentajea','PorcentajeController@aumentar')->name('porcentaje.aumentar');
Route::post('/porcentajed','PorcentajeController@disminuir')->name('porcentaje.disminuir');
Route::resource('aumentap','PorcentajeAumenta')->except(['create','store','destroy','show']);
Route::resource('restap','PorcentajeResta')->except(['create','store','destroy','show']);

app/Libro.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Libro extends Model
{
    protected $fillable=['autor_idÍndice','editorial_idÍndice','sigi_ISBN','sigi_titulo','sigi_anio','sigi_precio_venta','sigi_otros_autores','sigi_estado'];



    public function autor(){
        return $this->belongsTo('App\Autor');
    }

     public function editorial(){
    	return $this->belongsTo('App\Editorial');
    }


}

app/Http/Controllers/LibroController.php
<?php

namespace App\Http\Controllers;

use App\Libro;
use App\Editorial;
use App\Autor;
use Illuminate\Http\Request;

class LibroController extends Controller
{
    
     public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {
        $libro = Libro::all();
        $leer = $libro;

        $autor = Autor::all();
        $autores = $autor;

        $editorial = Editorial::all();
        $editoriales = $editorial;
        return view('libros.index',compact('leer','autores','editoriales'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       
      $autor = Autor::all();
        $autores = $autor;

        $editorial = Editorial::all();
        $editoriales = $editorial;
        return view('libros.create',compact('autores','editoriales'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $datos = [
            'autor_id' => 'required | ',
            'editorial_id' => 'required',
            'sigi_ISBN' => 'required | unique:libros',
            'sigi_titulo' => 'required | min:5 | max:20 | regex:/^[\pL\s\-]+$/u  |',
            'sigi_anio' => 'required | min: 4| max:4| alpha_num',
            'sigi_precio_venta' => 'required|max:22|regex:/^-?[0-9]+(?:\.[0-9]{1,2})?$/',
            'sigi_otros_autores' => 'max:50|regex:/(^[A-Za-z0-9-, ]+$)+/'

        ];
      
      $this->validate($request,$datos);
        $datosLibro=request()->except('_token');

          $datosLibro['sigi_titulo'] = strtoupper($request->get('sigi_titulo'));
          $datosLibro['sigi_otros_autores'] = strtoupper($request->get('sigi_otros_autores'));

        
         
        Libro::insert($datosLibro);
       
        return redirect('libro')->with([
            'Mensaje' => 'Libro Agregado'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Libro  $libro
     * @return \Illuminate\Http\Response
     */
    public function show(Libro $libro)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Libro  $libro
     * @return \Illuminate\Http\Response
     */
    public function edit( $id)
    {
        $autor = Autor::all();
        $autores = $autor;

        $editorial = Editorial::all();
        $editoriales = $editorial;

        $actualizar = Libro::findOrFail($id);
        return view('libros.edit',compact('actualizar','autores','editoriales'));
    
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Libro  $libro
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,  $id)
    {
       
        $datos = [
            'autor_id' => 'required | ',
            'editorial_id' => 'required',
            'sigi_ISBN' => 'required ',
            'sigi_titulo' => 'required | min:5 | max:20 | regex:/^[\pL\s\-]+$/u  |',
            'sigi_anio' => 'required | min: 4| max:4| alpha_num',
            'sigi_precio_venta' => 'required|max:22|regex:/^-?[0-9]+(?:\.[0-9]{1,2})?$/',
            'sigi_otros_autores' => 'max:50|regex:/(^[A-Za-z0-9-, ]+$)+/',
            'sigi_estado' => 'required'

        ];
      
      $this->validate($request,$datos);


       $datosLibro = request()->except('_token','_method'); 
       $datosLibro['sigi_titulo'] = strtoupper($request->get('sigi_titulo'));
       $datosLibro['sigi_otros_autores'] = strtoupper($request->get('sigi_otros_autores'));
        
       Libro::whereId($id)->update($datosLibro);
       
       return redirect("libro")->with([
        'Mensaje' => 'Libro actualizado'
       ]);    
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Libro  $libro
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Libro::whereId($id)->delete();
       
        return redirect('/libro')->with([
        'Mensaje' => 'Libro Eliminado',
         ]);
    }
}

resources/views/libros/PorcentajeAumenta.blade.php
@extends('layouts.plantilla')
@section('styles')


@endsection    
 
@section('content')
		
		<div class="row">
			    <div class="col-lg-12 ">
			        <div class="panel">
			            <div class="panel-heading">
			                <h3 class="panel-title">Aumentar Porcentaje del libro {{ $actualizar->sigi_titulo }}
			                  Valor $ {{ $actualizar->sigi_precio_venta }}
			                </h3>

			            </div>
			
			
			       
			            <!--===================================================-->
			            <form  action="{{ route('aumentap.update', $actualizar->id) }}" onsubmit="return validacionPorcentaje()"  method="post" class="panel-body form-horizontal form-padding">
			            	@csrf
			            	@method('PUT')
			            	@include('libros.formPorcentajeIndividual',['mensaje'=>'aumentar'])
               		 </div>
			            </form>
			            <!--===================================================-->
			            <!-- END BASIC FORM ELEMENTS -->
			
			
			        </div>
			    </div>

					   
		</div>
    


	
@endsection  
    
    


 @section('scripts')  
    
   
  


@endsection

resources/views/libros/PorcentajeResta.blade.php
@extends('layouts.plantilla')
@section('styles')


@endsection    
 
@section('content')
		
		<div class="row">
			    <div class="col-lg-12 ">
			        <div class="panel">
			            <div class="panel-heading">
			                <h3 class="panel-title">Restar Precio del libro {{ $actualizar->sigi_titulo }}
			                  Valor $ {{ $actualizar->sigi_precio_venta }}
			                </h3>

			            </div>
			
			
			       
			            <!--===================================================-->
			            <form  action="{{ route('restap.update', $actualizar->id) }}" onsubmit="return validacionPorcentaje()"  method="post" class="panel-body form-horizontal form-padding">
			            	@csrf
			            	@method('PUT')
			            	@include('libros.formPorcentajeIndividual',['mensaje'=>'restar'])
               		 </div>
			            </form>
			            <!--===================================================-->
			            <!-- END BASIC FORM ELEMENTS -->
			
			
			        </div>
			    </div>

					   
		</div>
    


	
@endsection  
    
    


 @section('scripts')  
    
   
  


@endsection

resources/views/libros/create.blade.php
@extends('layouts.plantilla')
@section('styles')


@endsection    
 
@section('content')
		
		<div class="row">
			    <div class="col-lg-12 ">
			        <div class="panel">
			            <div class="panel-heading">
			                <h3 class="panel-title">Agregar Informacion del libro</h3>
			            </div>
			
			
			       
					 <form action="{{ route('libro.store') }}" onsubmit="return validacionLibro()" method="post" class="panel-body form-horizontal form-padding">
                        @csrf
                        <!--Static-->
                        @include('libros.form',['mensaje'=> 'crear'])
                                    
                     </form>
			
			        </div>
			    </div>

					   
		</div>
    
		<!-- MODAL -->
		 <div class="modal fade" id="modal-isbn" role="dialog" tabindex="-1" aria-labelledby="demo-default-modal" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">

                <!--Modal header-->
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><i class="pci-cross pci-circle"></i></button>
                    <h4 class="modal-title text-center">Ejemplos de isbn </h4>
                </div>

                <!--Modal body-->
                <div class="modal-body">
                    <ul class="list-group">
					 

					  
					  <li class="list-group-item list-group-item-primary">99921-58-10-7</li>
					  <li class="list-group-item list-group-item-secondary">960 425 059 0</li>
					  <li class="list-group-item list-group-item-success">9780306406157</li>
					  <li class="list-group-item list-group-item-info">978-0-306-40615-7</li>	
					</ul>                   
                </div>

                <!--Modal footer-->
             
            </div>
        </div>
    </div>

	
@endsection  
    
    


 @section('scripts')  
    
   
  


@endsection

resources/views/libros/edit.blade.php
@extends('layouts.plantilla')
@section('styles')


@endsection    
 
@section('content')
@include("partials.validacionLibro")
@include("partials.validacionISBN")
		
		<div class="row">
			    <div class="col-lg-12 ">
			        <div class="panel">
			            <div class="panel-heading">
			                <h3 class="panel-title">Editar Informacion del libro</h3>
			            </div>
			
			
			       
			            <!--===================================================-->
			            <form  action="{{ route('libro.update', $actualizar->id) }}" onsubmit="return validacionLibro()" method="post" class="panel-body form-horizontal form-padding">
			            	@csrf
			            	@method('PUT')


			         
			     


		           <div class="form-group">
	                <label class="col-md-3 control-label" for="demo-text-input">Autor</label>
	                    <div class="col-md-9">
	                        <select class="form-control" name="autor_id">
	                        	@forelse($autores as $autor)
	                        	
	                        		<option value="{{ $autor->id }}" @if($autor->id == $actualizar->autor_id) selected="" @endif>{{ $autor->sigi_nombres. ' '.$autor->sigi_apellidos }}</option>
	                        	@empty
	                        	<span class="text-danger">No se encontraron roles</span>

	                        	@endforelse
	                        </select>
	                        @error('autor_id')
	                        <small class="help-block text-danger">{{ $message }}</small>
	                        @enderror
	                    </div>
	            	 </div>	


			   
		             <div class="form-group">
		                <label class="col-md-3 control-label" for="demo-text-input">Seleccione Editorial</label>
		                    <div class="col-md-9">
		                        <select class="form-control" name="editorial_id">
		                        	@forelse($editoriales as $editorial)
		                        	
		                        		<option value="{{ $editorial->id }}" @if($editorial->id == $actualizar->editorial_id) selected="" @endif>{{ $editorial->sigi_nombre }}</option>


		                        	@empty
		                        	<span class="text-danger">No se encontraron roles</span>

		                        	@endforelse
		                        </select>
		                        @error('editorial_id')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		             </div>

			
			            <div class="form-group">
			                	<label class="col-md-3 control-label" for="demo-text-input">ISBN</label>
			                    <div class="col-md-9">
			                        <input type="text" required="" name="sigi_ISBN" id="isbn" onblur="run()" value="{{ isset($actualizar->sigi_ISBN) ? $actualizar->sigi_ISBN : '' }}" id="demo-text-input" class="form-control" placeholder="Ingrese ISBN">
			                        @error('sigi_ISBN')
			                        <small class="help-block text-danger">{{ $message }}</small>
			                        @enderror
			                    </div>
		                </div>
		
		             	

		                 <div class="form-group">
		                    <label class="col-md-3 control-label" for="demo-text-input">Titulo</label>
		                    <div class="col-md-9">
		                        <input type="text" id="titulo" name="sigi_titulo" value="{{ isset($actualizar->sigi_titulo) ? $actualizar->sigi_titulo : ''  }}"   id="demo-text-input" class="form-control" placeholder="Ingrese titulo">
		                        @error('sigi_titulo')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		                </div>

		                 <div class="form-group">
		                    <label class="col-md-3 control-label" for="demo-text-input">Año</label>
		                    <div class="col-md-9">
		                        <input type="text" id="anio" name="sigi_anio" value="{{ isset($actualizar->sigi_anio) ? $actualizar->sigi_anio : ''  }}"   id="demo-text-input" class="form-control" placeholder="Ingrese Año del libro">
		                        @error('sigi_anio')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		                </div>

		                 <div class="form-group">
		                    <label class="col-md-3 control-label" for="demo-text-input">Precio de venta</label>
		                    <div class="col-md-9">
		                        <input type="text" id="precio" name="sigi_precio_venta" value="{{ isset($actualizar->sigi_precio_venta) ? $actualizar->sigi_precio_venta : ''  }}"   id="demo-text-input" class="form-control" placeholder="Ingrese Precio de venta">
		                        @error('sigi_precio_venta')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		                </div>

		                   <div class="form-group">
		                    <label class="col-md-3 control-label" for="demo-text-input">Otros autores</label>
		                    <div class="col-md-9">
		                        <input  name="sigi_otros_autores"  style="resize: none" value="{{ isset($actualizar->sigi_otros_autores) ? $actualizar->sigi_otros_autores : ''  }}"   id="demo-text-input" class="form-control" placeholder="Ingrese otros autores">
		                        @error('sigi_otros_autores')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		                </div>

		                <div class="form-group">
		                    <label class="col-md-3 control-label" for="demo-email-input">Estado</label>
		                    <div class="col-md-9">
		                        <select name="sigi_estado" class="form-control">
		                        	<option>Seleccion de estado</option>	
		                        	<option value="A" @if($actualizar->sigi_estado == 'A') selected=""  @endif) >Activo</option>
		                        	<option value="I" @if($actualizar->sigi_estado == 'I') selected=""  @endif) >Inactivo</option>
		                        </select>
		                        @error('sigi_estado')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		                </div>
					
					              
					
					              
					
					              
					               
					 <div class="modal-footer">
	                    <a href="{{ route('libro.index') }}" class="btn btn-default" type="button">Close</a>
	                    <input type="submit" class="btn btn-primary"  onclick="return confirm('Desea Actualizar?')" value="Actualizar Libro" name="">
                    
               		 </div>
			            </form>
			            <!--===================================================-->
			            <!-- END BASIC FORM ELEMENTS -->
			
			
			        </div>
			    </div>

					   
		</div>
    


	
@endsection  
    
    


 @section('scripts')  
    
   
  


@endsection

resources/views/libros/formPorcentaje.blade.php
  
		<div class="form-group">
       		 <label class="col-md-4 control-label" for="demo-text-input">Porcentaje(Ejemplo 10, 20 Ingrese de esta forma por favor)</label>
            <div class="col-md-8">
                <input type="number"   name="sigi_porcentaje"  required="" onKeyPress="return soloNumeros(event)" onblur="validar()"  id="porcentaje" class="form-control" placeholder="Ingrese Procentaje">
                @error('sigi_porcentaje')
                <small class="help-block text-danger">{{ $message }}</small>
                @enderror
            </div>
        </div>

         <div class="modal-footer">
            <button data-dismiss="modal" class="btn btn-default" type="button">Close</button>
            <input type="submit"  class="btn btn-primary"  value="Aumentar Porcentaje a todos los  libros" name="">
        
   		 </div>

         <script type="text/javascript">
            function validar(){
                 var pocentaje = document.getElementById('procentaje').value;
                alert(porcentaje);
                return false;
            }
            
         </script>

      

resources/views/libros/formPorcentajeIndividual.blade.php
@include("partials.validacionPorcentaje")
		<div class="form-group">
       		 <label class="col-md-4 control-label" for="demo-text-input">Porcentaje(Ejemplo 10, 20 Ingrese de esta forma por favor)</label>
            <div class="col-md-8">
                <input type="text" required="" name="sigi_porcentaje"  id="porcentaje" onKeyPress="return soloNumeros(event)"  class="form-control" placeholder="Ingrese Procentaje">
                @error('sigi_porcentaje')
                <small class="help-block text-danger">{{ $message }}</small>
                @enderror
            </div>

             <div class="col-md-8">
                <input type="hidden" name="sigi_titulo"  value="{{ $actualizar->sigi_titulo }}" id="demo-text-input" class="form-control" placeholder="Ingrese Procentaje">
                @error('sigi_titulo')
                <small class="help-block text-danger">{{ $message }}</small>
                @enderror
            </div>

        </div>

         <div class="modal-footer">
            <a href="{{ route('libro.index') }}" class="btn btn-default" type="button">Close</a>
            <input type="submit" onclick="return confirm('Desea cambiar el porcentaje?')" class="btn btn-primary"  value="{{ $mensaje === 'aumentar' ? 'Aumentar ' : ' Disminuir' }} Porcentaje del libro" name="">
        
   	 	</div>

resources/views/libros/index.blade.php
@extends('layouts.plantilla')
@section('styles')
    <!--DataTables [ OPTIONAL ]-->
    <link href="{{ asset('admin/plugins/datatables/media/css/dataTables.bootstrap.css') }}" rel="stylesheet">
    <link href="{{ asset('admin/plugins/datatables/extensions/Responsive/css/responsive.dataTables.min.css') }}" rel="stylesheet">
     <!--Summernote [ OPTIONAL ]-->
    <link href="{{ asset('admin/plugins/summernote/summernote.min.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('admin/css/font-awesome.min.css') }}">
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    

@endsection 


 
@section('content')
        <div class="panel">
                        <div class="panel-heading">
                            <h3 class="panel-title"> 
                                <a  href="{{ route('libro.create') }}"  class="btn btn-warning btn-rounded " style="color: white">Agregar</a>

                                @auth 
                                @if(Auth::user()->role->sigi_nombre == 'ADMINISTRADOR') 
                                  <button data-target="#modal-aumentar" data-toggle="modal" class="btn btn-success btn-rounded">Porcentaje +</button>

                                  <button data-target="#modal-disminuir" data-toggle="modal" class="btn btn-danger btn-rounded">Porcentaje -</button>
                                @endif
                              @endauth
                            </h3>

                            
                             @if(Session::has('Mensaje'))
                                 <div class="panel-body demo-nifty-alert">
                                    
                                    <div class="row">
                                        <div class="col-sm-12">
                            
                                            <!-- Primary Alert -->
                                            <!--===================================================-->
                                            <div class="alert alert-primary">
                                                <button class="close" data-dismiss="alert"><i class="pci-cross pci-circle"></i></button>
                                                <strong>Mensaje!</strong>  {{ Session::get('Mensaje') }}
                                            </div>
                            
                                            <!-- Success Alert -->
                                            <!--===================================================-->
                                           
                            
                                        </div>
                                      
                                    </div>
                                 </div>
                                 
                               
                             @endif

                                    
                            

                              

                            
                        </div>
                        <div class="panel-body">
                            <table id="demo-dt-basic" class="table table-striped table-bordered" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th>Autor</th>  
                                        <th>Editorial</th>                                
                                        <th class="min-tablet">ISBN</th>
                                        <th class="min-desktop">Titulo</th>
                                        <th class="min-desktop">Año</th>
                                        <th class="min-desktop">Precio de venta</th>
                                         <th class="min-desktop">Otros autores</th>
                                        <th>Eliminar</th>
                                        <th>Editar</th>
                                        @auth @if(Auth::user()->role->sigi_nombre == 'ADMINISTRADOR')

                                         <th>Porcentaje</th>
                                        @endif
                                        @endauth
                                     
                                        
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($leer as $recorrer)
                                    <tr>
                                        <td> {{ isset($recorrer->autor->sigi_nombres) ? $recorrer->autor->sigi_nombres .' '. $recorrer->autor->sigi_apellidos   : '' }} 
                                        </td>
                                        <td>{{ isset($recorrer->editorial->sigi_nombre) ? $recorrer->editorial->sigi_nombre : '' }}
                                        </td>

                                        <td>{{ $recorrer->sigi_ISBN }}</td>
                                        <td>{{ $recorrer->sigi_titulo }}</td>
                                        <td>{{ $recorrer->sigi_anio }}</td>
                                        <td>{{ $recorrer->sigi_precio_venta }}</td>
                                        <td>{{ $recorrer->sigi_otros_autores }}</td>
                                        <td>
                                            <form action="{{ route('libro.destroy',$recorrer->id) }}" method="post">
                                                @csrf
                                                @method('DELETE')
                                                  <button class="btn btn-success btn-icon" onclick="return confirm('Desea Eliminar?')"><i class="demo-psi-recycling icon-lg"></i></button>
                                            </form> 
                                            
                                        </td>
                                        <td>  
                                         

                                        
                                       
                                            <a class="btn btn-mint btn-icon" href="{{ route('libro.edit',$recorrer->id) }}"><i class="demo-psi-pen-5 icon-lg"></i></a>
                                        </td>
                                      
                                    @if(Auth::user()->role->sigi_nombre == 'ADMINISTRADOR')

                                        <td>
                                            <a href="{{ route('aumentap.edit',$recorrer->id) }}" class="btn btn-success btn-icon icon-lg fa fa-chevron-up">
                                                
                                            </a>
                                        @if($recorrer->sigi_precio_venta > 1)    
                                            <a href="{{ route('restap.edit',$recorrer->id) }}" class="btn btn-danger btn-icon icon-lg fa fa-chevron-down">
                                        @else
                                            <span class="text-danger">No disminuir precio</span>        
                                        @endif        
                                            </a>
                                        </td>
                                    @endif   
                                   
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
        </div>


    

        <!-- MODALES -->

  

    <div class="modal fade" id="modal-aumentar" role="dialog" tabindex="-1" aria-labelledby="demo-default-modal" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">

                <!--Modal header-->
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><i class="pci-cross pci-circle"></i></button>
                    <h4 class="modal-title text-center">Aumentar porcentaje a todos los Libros </h4>
                </div>

                <!--Modal body-->
                <div class="modal-body">
                     <form action="{{ route('porcentaje.aumentar') }}"  method="post" class="panel-body form-horizontal form-padding">
                        @csrf
                        <!--Static-->
                        @include('libros.formPorcentaje')
                                    
                     </form>
                   
                </div>

                <!--Modal footer-->
             
            </div>
        </div>
    </div>

     <div class="modal fade" id="modal-disminuir" role="dialog" tabindex="-1" aria-labelledby="demo-default-modal" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">

                <!--Modal header-->
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><i class="pci-cross pci-circle"></i></button>
                    <h4 class="modal-title text-center">Disminuir porcentaje a todos los Libros </h4>
                </div>

                <!--Modal body-->
                <div class="modal-body">
                     <form action="{{ route('porcentaje.disminuir') }}" onsubmit="return validacionPorcentaje()"  method="post" class="panel-body form-horizontal form-padding">
                        @csrf
                        <!--Static-->
                        @include('libros.formPorcentajeDisminuir')
                                    
                     </form>
                   
                </div>

                <!--Modal footer-->
             
            </div>
        </div>
    </div>

  

@endsection  
    
    
 

 @section('scripts')  
    
   
    <!--DataTables [ OPTIONAL ]-->
    <script src="{{ asset('admin/plugins/datatables/media/js/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('admin/plugins/datatables/media/js/dataTables.bootstrap.js') }}"></script>
    <script src="{{ asset('admin/plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js') }}"></script>


    <!--DataTables Sample [ SAMPLE ]-->
    <script src="{{ asset('admin/js/demo/tables-datatables.js') }}"></script>

        <!--Summernote [ OPTIONAL ]-->
    <script src="{{ asset('admin/plugins/summernote/summernote.min.js') }}"></script>


    <!--Form File Upload [ SAMPLE ]-->
    <script src="{{ asset('admin/js/demo/form-text-editor.js') }}"></script>



@endsection