routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes([
	'register' => false,
	
]);

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/autor','AutorController')->except(['show']);
Route::resource('/editorial','EditorialController')->except(['show']);
Route::resource('/rol','RoleController')->except(['show']);
Route::resource('/usuario','UsuarioController')->except(['show']);
Route::resource('/libro','LibroController')->except(['show']);
Route::post('/porcentajea','PorcentajeController@aumentar')->name('porcentaje.aumentar');
Route::post('/porcentajed','PorcentajeController@disminuir')->name('porcentaje.disminuir');
Route::resource('aumentap','PorcentajeAumenta')->except(['create','store','destroy','show']);
Route::resource('restap','PorcentajeResta')->except(['create','store','destroy','show']);

resources/views/editoriales/create.blade.php
@extends('layouts.plantilla')
@section('styles')


@endsection    
 
@section('content')
@include("partials.validacionEditorial")		
		<div class="row">
			    <div class="col-lg-12 ">
			        <div class="panel">
			            <div class="panel-heading">
			                <h3 class="panel-title">Agregar Informacion de la Editorial</h3>
			            </div>
			
			
			            <!-- BASIC FORM ELEMENTS -->
			            <!--===================================================-->
			         <form action="{{ route('editorial.store') }}" onsubmit="return validacionEditorial()" method="post" class="panel-body form-horizontal form-padding">
                        @csrf
                        <!--Static-->
                        @include('editoriales.form',['mensaje'=> 'crear'])
                                    
                     </form>
			            <!--===================================================-->
			            <!-- END BASIC FORM ELEMENTS -->
			
			
			        </div>
			    </div>

					   
		</div>
    


	
@endsection  
    
    


 @section('scripts')  
    
   
  


@endsection

resources/views/editoriales/edit.blade.php
@extends('layouts.plantilla')
@section('styles')


@endsection    
 
@section('content')
@include("partials.validacionEditorial")		
		<div class="row">
			    <div class="col-lg-12 ">
			        <div class="panel">
			            <div class="panel-heading">
			                <h3 class="panel-title">Editar Informacion de la Editorial</h3>
			            </div>
			
			
			            <!-- BASIC FORM ELEMENTS -->
			            <!--===================================================-->
			            <form onsubmit="return validacionEditorial()"  action="{{ route('editorial.update', $actualizar->id) }}" method="post" class="panel-body form-horizontal form-padding">
			            	@csrf
			            	@method('PUT')
			
			                 					 <div class="form-group">
		                <label class="col-md-3 control-label" for="demo-text-input">Nombre Editorial</label>
		                    <div class="col-md-9">
		                        <input type="text" id="editorial" name="sigi_nombre" value="{{ isset($actualizar->sigi_nombre) ? $actualizar->sigi_nombre : '' }}" id="demo-text-input" class="form-control" placeholder="Ingrese nombre editorial">
		                        @error('sigi_nombre')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		                </div>
		
		             	

		                 <div class="form-group">
		                    <label class="col-md-3 control-label" for="demo-text-input">Email</label>
		                    <div class="col-md-9">
		                        <input type="text" id="email" name="sigi_email" value="{{ isset($actualizar->sigi_email) ? $actualizar->sigi_email : ''  }}"   id="demo-text-input" class="form-control" placeholder="Ingrese Email">
		                        @error('sigi_email')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		                </div>

		                <div class="form-group">
		                    <label class="col-md-3 control-label" for="demo-email-input">Estado</label>
		                    <div class="col-md-9">
		                        <select name="sigi_estado" class="form-control">
		                        	<option>Seleccion de estado</option>	
		                        	<option value="A" @if($actualizar->sigi_estado == 'A') selected=""  @endif) >Activo</option>
		                        	<option value="I" @if($actualizar->sigi_estado == 'I') selected=""  @endif) >Inactivo</option>
		                        </select>
		                        @error('sigi_estado')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		                </div>
					
					              
					
					              
					
					              
					               
					 <div class="modal-footer">
	                    <a href="{{ route('editorial.index') }}" class="btn btn-default" type="button">Close</a>
	                    <input type="submit" class="btn btn-primary"  onclick="return confirm('Desea Actualizar?')" value="Actualizar Editorial" name="">
                    
               		 </div>
			    </form>
			            <!--===================================================-->
			            <!-- END BASIC FORM ELEMENTS -->
			
			
			        </div>
			    </div>

					   
		</div>
    


	
@endsection  
    
    


 @section('scripts')  
    
   
  


@endsection

resources/views/editoriales/form.blade.php
@include("partials.validacionEditorial")
  					 <div class="form-group">
		                <label class="col-md-3 control-label" for="demo-text-input">Nombre Editorial</label>
		                    <div class="col-md-9">
		                        <input type="text" id="editorial" value="{{ old('sigi_nombre') }}" name="sigi_nombre"  id="demo-text-input" class="form-control" placeholder="Debe Comenzar por la primera letra Mayuscula">
		                        @error('sigi_nombre')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		                </div>
		
		             
		            <div class="form-group">
		                    <label class="col-md-3 control-label" for="demo-text-input">Email</label>
		                    <div class="col-md-9">
		                        <input type="text" id="email" value="{{ old('sigi_email') }}" name="sigi_email"    id="demo-text-input" class="form-control" placeholder="Ingrese Email">
		                        @error('sigi_email')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		            </div>
					
					              
					
					              
					
					              
					               
					 <div class="modal-footer">
	                    <a href="{{ route('editorial.index') }}" class="btn btn-default" type="button">Close</a>
	                    <input type="submit" class="btn btn-primary"  onclick="return confirm('Desea Agregar?')" value="Crear Editorial" name="">
                    
               		 </div>

resources/views/editoriales/index.blade.php
@extends('layouts.plantilla')
@section('styles')
    <!--DataTables [ OPTIONAL ]-->
    <link href="{{ asset('admin/plugins/datatables/media/css/dataTables.bootstrap.css') }}" rel="stylesheet">
    <link href="{{ asset('admin/plugins/datatables/extensions/Responsive/css/responsive.dataTables.min.css') }}" rel="stylesheet">

    

@endsection    
 


@section('content')
        <div class="panel">
                        <div class="panel-heading">
                            <h3 class="panel-title"> 
                                <a href="{{ route('editorial.create') }}"  class="btn btn-warning btn-rounded" style="color:white;">Agregar</a>
                            </h3>

                            @if(Session::has('Mensaje'))
                                 <div class="panel-body demo-nifty-alert">
                                    
                                    <div class="row">
                                        <div class="col-sm-12">
                            
                                            <!-- Primary Alert -->
                                            <!--===================================================-->
                                            <div class="alert alert-primary">
                                                <button class="close" data-dismiss="alert"><i class="pci-cross pci-circle"></i></button>
                                                <strong>Mensaje!</strong>  {{ Session::get('Mensaje') }}
                                            </div>
                            
                                            <!-- Success Alert -->
                                            <!--===================================================-->
                                           
                            
                                        </div>
                                      
                                    </div>
                                 </div>
                               
                             @endif
                        </div>
                        <div class="panel-body">
                            <table id="demo-dt-basic" class="table table-striped table-bordered" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th>Nombres Editorial</th>                                 
                                        <th class="min-tablet">Email</th>
                                        <th class="min-desktop">Estado</th>
                                        <th>Eliminar</th>
                                        <th>Editar</th>
                                     
                                        
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($leer as $recorrer)
                                    <tr>
                                        <td>{{ $recorrer->sigi_nombre }}</td>
                                        <td>{{ $recorrer->sigi_email }}</td>
                                        <td>{{ $recorrer->sigi_estado }}</td>
                                        <td>
                                            <form action="{{ route('editorial.destroy',$recorrer->id) }}" method="post">
                                                @csrf
                                                @method('DELETE')
                                                  <button class="btn btn-success btn-icon" onclick="return confirm('Desea Eliminar?')"><i class="demo-psi-recycling icon-lg"></i></button>
                                            </form> 
                                            
                                        </td>
                                        <td>  
                                         

                                        
                                       
                                            <a class="btn btn-mint btn-icon" href="{{ route('editorial.edit',$recorrer->id) }}"><i class="demo-psi-pen-5 icon-lg"></i></a>
                                        </td>

                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
        </div>


    

        <!-- MODALES -->

   
@endsection  
    
    
 

 @section('scripts')  
    
   
    <!--DataTables [ OPTIONAL ]-->
    <script src="{{ asset('admin/plugins/datatables/media/js/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('admin/plugins/datatables/media/js/dataTables.bootstrap.js') }}"></script>
    <script src="{{ asset('admin/plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js') }}"></script>


    <!--DataTables Sample [ SAMPLE ]-->
    <script src="{{ asset('admin/js/demo/tables-datatables.js') }}"></script>


@endsection